Hw01 hello otus
IskenT/hw_golang pull request #1
Opened 2023-08-02 16:57 UTC by IskenT

2023-08-02 19:33 UTC, ityulkanov requested changes

2023-08-02 19:33 UTC, ityulkanov commented on hw01_hello_otus/go.mod
> +module github.com/hw_golang/hw01_hello_otus
необходимо указывать путь к модулю в формате имя пользователя / имф репозитория / имя папки

2023-08-03 04:52 UTC, ityulkanov approved these changes
Не забудьте также удалить .sync файл

2023-08-05 17:17 UTC, IskenT commented
Merged 05.08.2023 to main

2023-08-05 17:17 UTC, merged